

export {default as Header} from './Header/Header'
export {default as SpeedDial} from './MainScreen/SpeedDial/SpeedDial'
export {ClassesContent} from './MainScreen/Content/ClassesContent'
export {default as Login} from './LoginRegister/Login'
export {default as Register} from './LoginRegister/Register'
export {default as ClassDetail} from './ClassDetail/Stream/ClassDetailContent'
export {People} from './ClassDetail/People/People'
export {Classwork} from './ClassDetail/Classwork/Classwork'
export {ShowGrade} from './ShowGrade/ShowGrade'
export {GradeStructure} from './ClassDetail/GradeStructure/GradeStructure'
export {Grade} from './ClassDetail/Grade/Grade'
export {StudentGrade} from './ClassDetail/StudentGrade/StudentGrade'
export {AdminPage} from './Admin/index'
